### ISSUE TITLE
Image Uploader not Working

### ISSUE THREAD

**Issue by chrisjmccrum** [datasets-at/mi-wordpress#6]
I imported this dataset (0.1.3) into fifo and everything was working fine with the internal ip address.  I uploaded a theme and then in the wordpress admin panel assigned the wordpress site my public url instead.  The site loads but when I go to the media uploader i get a generic wordpress http error. 

The wordpress-error.log says this tho:

```
  thrown in /opt/local/www/wordpress/wp-content/plugins/wr-contactform/libraries/init/plugin.php on line 80" while reading response header from upstream, client: 10.1.3.107, server: _, request: "POST /wp-admin/async-upload.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.kingofkingswm.com", referrer: "http://www.kingofkingswm.com/wp-admin/upload.php"
2016/05/19 18:20:19 [error] 93950#0: *29 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function iconv() in /opt/local/www/wordpress/wp-content/plugins/wr-contactform/libraries/init/plugin.php:80
Stack trace:
#0 /opt/local/www/wordpress/wp-includes/plugin.php(235): WR_CF_Init_Plugin::wp_handle_upload_prefilter(Array)
#1 /opt/local/www/wordpress/wp-admin/includes/file.php(257): apply_filters('wp_handle_uploa...', Array)
#2 /opt/local/www/wordpress/wp-admin/includes/file.php(441): _wp_handle_upload(Array, Array, '2016-05-19 18:2...', 'wp_handle_uploa...')
#3 /opt/local/www/wordpress/wp-admin/includes/media.php(282): wp_handle_upload(Array, Array, '2016-05-19 18:2...')
#4 /opt/local/www/wordpress/wp-admin/media-new.php(31): media_handle_upload('async-upload', 0)
#5 {main}
  thrown in /opt/local/www/wordpress/wp-content/plugins/wr-contactform/libraries/init/plugin.php on line 80" while reading response header from upstream, client: 10.1.3.107, server: _, request: "POST /wp-admin/media-new.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.kingofkingswm.com", referrer: "http://www.kingofkingswm.com/wp-admin/media-new.php"

```

I was hoping you might have some insight on how to fix this error so I can upload assets to my new wordpress site.

**Comment by MerlinDMC** [comment]
Looks like the iconv pecl module is missing or not activated. I'm not a wordpress friend but @trentster probably knows what is wrong there since he was using that image to host his pages.

**Comment by chrisjmccrum** [comment]
@MerlinDMC thanks man - hopefully I can get some insight on how to activate/install it.  I'm still fairly new to all of this but learning slowly but surely
